---

- include_role: name=_include-exe_download_copy
  vars:
    arg_install_comment: "Monitoring Prometheus agent | jmx"
    arg_install_exe_fullpath: "{{ thisType.exe_fullpath }}"
    arg_install_exe_version: "{{ prometheus_agent_jmx_version }}"
    arg_install_exe_version_altcmd: "unzip -p {{ thisType.exe_fullpath }}  META-INF/MANIFEST.MF"
    arg_install_exe_version_arg: " | grep -i 'Implementation-Version' "
    arg_install_exe_download_url: "{{ thisType.donwload_url }}"
    arg_install_exe_hash: "{{ prometheus_agent_jmx_version_hash }}"
    arg_install_exe_mode: "0644"
    arg_install_exe_version_same_for_all: "{{ prometheus_agent_version_same_for_all }}"


  loop_control:
    # required to prevent any conflict with the keyword "item" in the included tasks
    loop_var: thisType
  with_items:
    - { exe_fullpath: "{{ role_prometheus_agent_jmx_dist.bin }}",       donwload_url: "{{ role_prometheus_agent_jmx_package_url }}" }
    - { exe_fullpath: "{{ role_prometheus_agent_jmx_dist.bin_java6 }}", donwload_url: "{{ role_prometheus_agent_jmx_package_url_java6 }}" }


- name: Monitoring Prometheus agent | jmx - install service files
  template:
    src: "templates/{{ item.file }}.j2"
    dest: "{{ var_file_dest }}"
    owner: "{{ item.owner |default('root') }}"
    group: "{{ item.group |default( item.owner | default('root') ) }}"
    mode: "{{ item.mode |default('0644') }}"
  vars:
    var_file_dest: "{{ item.dest |default(item.file) }}"
  with_items:
    - { file: "{{ role_prometheus_agent_jmx_dist.config }}" }
  loop_control:
    label: "file: {{ var_file_dest }}"
  register: task_config_status
  become: yes


# no service to manage - the agents are jar files to inject in the java command line

