---

- name: Monitoring Prometheus agent | snmp - requirements
  include_role: name=_include-pkg_install
  vars:
    arg_install_comment: "Monitoring Prometheus agent | snmp"
    arg_install_packages: "{{ role_prometheus_agent_snmp_requirements }}"


- include_role: name=_include-exe_download_copy
  vars:
    arg_install_comment: "Monitoring Prometheus agent | snmp"
    arg_install_exe_fullpath: "{{ role_prometheus_agent_snmp_dist.bin }}"
    arg_install_exe_version: "{{ prometheus_agent_snmp_version }}"
    # snmp exporter does not have a version flag => chain echo with the version instead
    # TODO: reactivate --version when fixed on snmp side
    # arg_install_exe_version_arg: "--version"
    arg_install_exe_version_arg: "-h && echo 'skip me {{ prometheus_agent_snmp_version }}'"
    arg_install_exe_download_url: "{{ role_prometheus_agent_snmp_package_url }}"
    arg_install_exe_hash: "{{ prometheus_agent_snmp_version_hash }}"
    arg_install_exe_is_compressed_archive: yes
    arg_install_exe_compressed_archive_binaries_to_link: [ "{{ role_prometheus_agent_snmp_dist.bin |basename }}" ]
    arg_install_exe_service: "{{ role_prometheus_agent_snmp_dist.service }}"


- name: Monitoring Prometheus agent | snmp - install service files
  template:
    src: "templates/{{ item.file }}.j2"
    dest: "{{ var_file_dest }}"
    owner: "{{ item.owner |default('root') }}"
    group: "{{ item.group |default( item.owner | default('root') ) }}"
    mode: "{{ item.mode |default('0644') }}"
  vars:
    var_file_dest: "{{ item.dest |default(item.file) }}"
  with_items:
    - { file: "/etc/systemd/system/{{ role_prometheus_agent_snmp_dist.service }}" }
    - { file: "{{ role_prometheus_agent_snmp_dist.service_conf }}" }
  loop_control:
    label: "file: {{ var_file_dest }}"
  notify: "reload systemd-daemon"
  register: task_config_status
  become: yes


- name: Monitoring Prometheus agent | snmp - storage directory for custom mibs
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
    - "{{ role_prometheus_agent_snmp_dist.mibs }}"


- name: Monitoring Grafana | provisioning - custom mibs file copy
  copy:
    src: "{{ item.source }}"
    dest: "{{ var_mibs_dest }}"
    owner: "root"
    mode: '0644'
  vars:
    var_mibs_dest: "{{ role_prometheus_agent_snmp_dist.mibs }}/{{ item )}"
  loop_control:
    label: "source: {{ item }}, dest: {{ var_mibs_dest }}"
  with_items: "{{ prometheus_agent_snmp_mibs_deploy_files }}"
  register: task_mibs_status


# force the notify handlers to execute now
- meta: flush_handlers


# _pkg_download_copy_status is generated by _include-exe_download_copy
- name: Monitoring Prometheus agent | snmp - stop service on version change
  service:
    name: "{{ role_prometheus_agent_snmp_dist.service }}"
    state: "stopped"
  when: >
    task_config_status is changed
    or task_config_global is changed
    or task_mibs_status is changed
  become: yes


# enabled is forced, as depending of the version, the agent can be installed in a disabled state
- name: Monitoring Prometheus agent | snmp - enable and start the service
  service:
    name: "{{ role_prometheus_agent_snmp_dist.service }}"
    state: started
    enabled: yes
  become: yes

