---

- name: Vaultwarden | config - create directory requirements
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner |default('root') }}"
    group: "{{ item.group |default( item.owner | default('root') ) }}"
    mode: "{{ item.mode |default('0755') }}"
    recurse: no
  with_items:
    - { path: "{{ vaultwarden_install_dir }}/data",  mode: "750" }
    - { path: "{{ vaultwarden_install_dir }}/log" }


- name: Vaultwarden | config - docker image deployement
  include_role: name=_include-compose_deploy
  vars:
    arg_compose_comment: "Vaultwarden"
    arg_compose_deploy_dir: "{{ vaultwarden_install_dir }}"
    arg_compose_main_template: "templates/docker-compose.yml.j2"
    arg_compose_env_template: "templates/vaultwarden.conf.j2"
    arg_compose_force_stop_on_change: yes
    arg_compose_conf_sensitive: yes
    arg_compose_managed_by_ansible: yes
    arg_compose_remove_old_images: yes


- name: Vaultwarden | config - logrotate
  template:
    src: "templates/{{ item.file }}.j2"
    dest: "{{ item.file }}"
    owner: "{{ item.owner |default('root') }}"
    group: "{{ item.group |default( item.owner | default('root') ) }}"
    mode: "{{ item.mode |default('0644') }}"
    force: "{{ item.force |default(omit) }}"
  with_items:
    - { file: "/etc/logrotate.d/vaultwarden" }


- name: Vaultwarden | system - create symlink requirements
  file:
    src: "{{ item.src }}"
    state: link
    owner: root
    group: root
    dest: "{{ item.link }}"
    force: yes
    follow: false
  with_items:
    - { src: "{{ vaultwarden_install_dir }}/log",  link: "/var/log/vaultwarden" }
  when: item.link | default('') != item.src


- name: Vaultwarden | service - enable and start the systemd service
  systemd:
    name: "docker-compose@{{ vaultwarden_install_dir |basename  }}.service"
    enabled: yes
    state: started
  when: vaultwarden_use_compose_service |bool

