---

# this will also validate the configuration
- name: restart apache validate config
  shell: /usr/sbin/apachectl -t
  become: yes
  notify: restart apache service


- name: reload apache validate config
  shell: /usr/sbin/apachectl -t
  become: yes
  notify: reload apache service


# on some distro a restart is just a reload - ensure the service will stop
- name: restart apache service
  service:
    name: "{{ role_apache_dist.service }}"
    state: stopped
  notify: start apache service


- name: start apache service
  service:
    name: "{{ role_apache_dist.service }}"
    state: started


- name: reload apache service
  service:
    name: "{{ role_apache_dist.service }}"
    state: reloaded

