---

- name: System Update | parameters validation
  assert:
    that:
      - system_package_update_mode |length > 0
      - system_package_update_mode in role_supported_modes
    fail_msg: "Error: one of the mandatory parameters is either not set, empty, or with an unexpected value"
    quiet: yes


# package install role => system & network tools
- name: System Update | requirements
  include_role: name=_include-pkg_install
  vars:
    arg_install_comment: "System Update | requirements"
    arg_install_packages: "{{ role_pkg_install_reqs }}"


# Packages updates
- name: System Update | load the corresponding family tasks
  include_tasks: "{{ include_item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family|lower }}.yml"
      - "defaults.yml"
      paths:
      - "debian/"
      - "redhat/"
      - "unknown/"
  loop_control:
    loop_var: include_item


#  Using import_tasks with an empty file raise a warning message - this does not happen with include_tasks
- name: System Update | load custom tasks before reboot
  include_tasks: custom_pre_reboot.yml
  when: task_reboot_required is defined and task_reboot_required is changed


# force the notify handlers to execute now
- meta: flush_handlers
