---

# this will move the directories from the default location to the new location
# and create redirecting symlinks

- name: PostgreSQL | move location - config dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "PostgreSQL - conf"
    # force the use of the normalized conf location
    arg_move_data_source_path: "{{ role_postgresql_dist.conf_normalized }}"
    arg_move_data_dest_path: "{{ postgresql_conf_dir }}"
    arg_move_data_dest_owner: "{{ role_postgresql_dist.user }}"
    arg_move_data_dest_group: "{{ role_postgresql_dist.user }}"
    arg_move_data_dest_mode: "{{ role_postgresql_dist.conf_mode }}"
    arg_move_data_service_stop: "{{ role_postgresql_dist.service }}"
    arg_move_data_both_exist_fail: "{{ not ( postgresql_move_data_both_exist_ignore_source |bool ) }}"
    arg_move_data_both_exist_delete_source: "{{ postgresql_move_data_both_exist_ignore_source |bool }}"
  when: role_postgresql_dist.conf != postgresql_conf_dir


- name: PostgreSQL | move location - data dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "PostgreSQL - data"
    arg_move_data_source_path: "{{ role_postgresql_dist.data }}"
    arg_move_data_dest_path: "{{ postgresql_data_dir }}"
    arg_move_data_dest_owner: "{{ role_postgresql_dist.user }}"
    arg_move_data_dest_group: "{{ role_postgresql_dist.group }}"
    arg_move_data_dest_owner_group_update_recursive: yes
    arg_move_data_dest_mode: "{{ role_postgresql_dist.data_mode }}"
    arg_move_data_service_stop: "{{ role_postgresql_dist.service }}"
    arg_move_data_both_exist_fail: "{{ not ( postgresql_move_data_both_exist_ignore_source |bool ) }}"
    arg_move_data_both_exist_delete_source: "{{ postgresql_move_data_both_exist_ignore_source |bool }}"
  when: role_postgresql_dist.data != postgresql_data_dir


- name: PostgreSQL | move location - log dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "PostgreSQL - log"
    arg_move_data_source_path: "{{ role_postgresql_dist.log }}"
    arg_move_data_dest_path: "{{ postgresql_log_dir }}"
    arg_move_data_dest_owner: "{{ role_postgresql_dist.log_user }}"
    arg_move_data_dest_group: "{{ role_postgresql_dist.log_group }}"
    arg_move_data_dest_owner_group_update_recursive: yes
    arg_move_data_dest_mode: "{{ role_postgresql_dist.log_mode }}"
    arg_move_data_service_stop: "{{ role_postgresql_dist.service }}"
    arg_move_data_both_exist_fail: "{{ not ( postgresql_move_data_both_exist_ignore_source |bool ) }}"
    arg_move_data_both_exist_delete_source: "{{ postgresql_move_data_both_exist_ignore_source |bool }}"
  when: role_postgresql_dist.log != postgresql_log_dir

