---

# this will move the directories from the default location to the new location
# and create redirecting symlinks

- name: Monitoring Prometheus | move location - config dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "Monitoring Prometheus - conf"
    arg_move_data_source_path: "{{ role_prometheus_dist.conf }}"
    arg_move_data_dest_path: "{{ prometheus_conf_dir }}"
    arg_move_data_dest_owner: "root"
    arg_move_data_dest_group: "root"
    arg_move_data_dest_mode: "755"
    arg_move_data_service_stop: "{{ role_prometheus_dist.service }}"
    arg_move_data_both_exist_fail: no
    arg_move_data_both_exist_delete_source: yes
  when: role_prometheus_dist.conf != prometheus_conf_dir


- name: Monitoring Prometheus | move location - data dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "Monitoring Prometheus - data"
    arg_move_data_source_path: "{{ role_prometheus_dist.data }}"
    arg_move_data_dest_path: "{{ prometheus_data_dir }}"
    arg_move_data_dest_owner: "{{ role_prometheus_dist.user }}"
    arg_move_data_dest_group: "{{ role_prometheus_dist.user }}"
    arg_move_data_dest_mode: "755"
    arg_move_data_service_stop: "{{ role_prometheus_dist.service }}"
    arg_move_data_both_exist_fail: no
    arg_move_data_both_exist_delete_source: yes
  when: role_prometheus_dist.data != prometheus_data_dir

