---

# this will move the directories from the default location to the new location
# and create redirecting symlinks

- name: MySQL/MariaDB | move location - config dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "MySQL/MariaDB - conf"
    arg_move_data_source_path: "{{ role_mysql_dist.conf_to_move }}"
    arg_move_data_dest_path: "{{ mysql_conf_dir }}"
    arg_move_data_dest_owner: "root"
    arg_move_data_dest_group: "root"
    arg_move_data_dest_mode: "{{ role_mysql_dist.conf_mode }}"
    arg_move_data_service_stop: "{{ role_mysql_dist.service }}"
    arg_move_data_both_exist_fail: "{{ not ( mysql_move_data_both_exist_ignore_source |bool ) }}"
    arg_move_data_both_exist_delete_source: "{{ mysql_move_data_both_exist_ignore_source |bool }}"
  when: role_mysql_dist.conf != mysql_conf_dir


- name: MySQL/MariaDB | move location - data dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "MySQL/MariaDB - data"
    arg_move_data_source_path: "{{ role_mysql_dist.data }}"
    arg_move_data_dest_path: "{{ mysql_data_dir }}"
    arg_move_data_dest_owner: "{{ role_mysql_dist.user }}"
    arg_move_data_dest_group: "{{ role_mysql_dist.group }}"
    arg_move_data_dest_owner_group_update_recursive: yes
    arg_move_data_dest_mode: "{{ role_mysql_dist.data_mode }}"
    arg_move_data_service_stop: "{{ role_mysql_dist.service }}"
    arg_move_data_both_exist_fail: "{{ not ( mysql_move_data_both_exist_ignore_source |bool ) }}"
    arg_move_data_both_exist_delete_source: "{{ mysql_move_data_both_exist_ignore_source |bool }}"
  when: role_mysql_dist.data != mysql_data_dir


- name: MySQL/MariaDB | move location - log dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "MySQL/MariaDB - log"
    arg_move_data_source_path: "{{ role_mysql_dist.log }}"
    arg_move_data_dest_path: "{{ mysql_log_dir }}"
    arg_move_data_dest_owner: "{{ role_mysql_dist.log_user }}"
    arg_move_data_dest_group: "{{ role_mysql_dist.log_group }}"
    arg_move_data_dest_owner_group_update_recursive: yes
    arg_move_data_dest_mode: "{{ role_mysql_dist.log_mode }}"
    arg_move_data_service_stop: "{{ role_mysql_dist.service }}"
    arg_move_data_both_exist_fail: "{{ not ( mysql_move_data_both_exist_ignore_source |bool ) }}"
    arg_move_data_both_exist_delete_source: "{{ mysql_move_data_both_exist_ignore_source |bool }}"
  when: role_mysql_dist.log != mysql_log_dir

