---

# this will move the directories from the default location to the new location
# and create redirecting symlinks

- name: webserver apache | move location - config dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "webserver apache - config"
    arg_move_data_source_path: "{{ role_apache_dist.etc }}"
    arg_move_data_dest_path: "{{ apache_conf_dir }}"
    arg_move_data_dest_owner: "root"
    arg_move_data_dest_group: "root"
    arg_move_data_dest_mode: "0755"
    arg_move_data_service_stop: "{{ role_apache_dist.service }}"
    arg_move_data_both_exist_fail: no
    arg_move_data_both_exist_delete_source: yes
  when: role_apache_dist.etc != apache_conf_dir


- name: webserver apache | move location - data dir
  include_role: name=_include-data_move_location
  vars:
    arg_move_data_comment: "webserver apache - webroot"
    arg_move_data_source_path: "{{ role_apache_dist.web_root }}"
    arg_move_data_dest_path: "{{ apache_webroot_dir }}"
    arg_move_data_dest_owner: "{{ role_apache_dist.user }}"
    arg_move_data_dest_group: "{{ role_apache_dist.group }}"
    arg_move_data_dest_mode: "0755"
    arg_move_data_service_stop: "{{ role_apache_dist.service }}"
    arg_move_data_both_exist_fail: no
    arg_move_data_both_exist_delete_source: yes
  when: role_apache_dist.web_root != apache_webroot_dir

