---

# RHEL/Centos Apache2 package suffers from a total absence of enhancements
# these tasks will try to make the installation more closer to the debian configuration

- name: webserver apache | system - RHEL enhancement - directories structure
  file:
    path: "{{ item.path }}"
    state: directory
    recurse: no
    owner: "{{ item.owner |default( 'root' ) }}"
    group: "{{ item.group | default( item.owner |default( 'root' ) ) }}"
    mode: "{{ item.mode |default( '0755' ) }}"
  with_items:
    - { path: "{{ role_apache_dist.etc }}/conf-available" }
    - { path: "{{ role_apache_dist.etc }}/conf-enabled" }
    - { path: "{{ role_apache_dist.etc }}/mods-enabled" }
    - { path: "{{ role_apache_dist.etc }}/sites-available" }
    - { path: "{{ role_apache_dist.etc }}/sites-enabled" }
    - { path: "{{ role_apache_dist.lock }}",  owner: "{{ role_apache_dist.user }}",  group: "root",  mode: "0755" }


- name: webserver apache | system - RHEL enhancement - config structure
  file:
    src: "{{ item.src }}"
    dest: "{{ item.link }}"
    state: link
  vars:
  with_items:
  - { src: "{{ role_apache_dist.etc }}/conf.modules.d",  link: "{{ role_apache_dist.etc }}/mods-available" }
  # replace the relative path with an absolute path for the link
  - { src: "{{ role_apache_dist.log }}", link: "{{ role_apache_dist.etc }}/logs" }


- name: webserver apache | system - RHEL enhancement - module installation
  template:
    src: "templates/{{ dest_file }}.j2"
    dest: "{{ dest_file }}"
    mode: "0644"
    owner: "root"
    group: "root"
  vars:
    # reusing dest_file as src and dest for template
    dest_file: "{{ item |regex_replace('^.*templates/', '')  |regex_replace('\\.j2$', '') }}"
  with_items:
    # the .j2 extension is not mandatory due to dest_file used as src
    - "{{ query('fileglob', 'templates/{{ role_apache_dist.etc }}/mods-available/*.load.j2') |sort }}"
    - "{{ query('fileglob', 'templates/{{ role_apache_dist.etc }}/mods-available/*.conf.j2') |sort }}"
    - "{{ role_apache_dist.etc }}/conf/mods-enabled_loader.conf"
    - "{{ role_apache_dist.etc }}/envvars"
    - "{{ role_apache_dist.etc }}/conf.d/THIS_DIRECTORY_IS_NOT_USED"
  loop_control:
    label: "file: {{ dest_file }}"
  notify: reload apache validate config


- name: webserver apache | system - RHEL enhancement - default module activation
  file:
    src: "{{ role_apache_dist.etc }}/mods-available/{{ item }}"
    dest: "{{ role_apache_dist.etc }}/mods-enabled/{{ item }}"
    state: link
  vars:
  with_items:
    - "00-systemd.conf"
    - "00-mpm.conf"
    - "10-h2.conf"
    # - "10-proxy_h2.conf"  <= raise an error due to mod_proxy missing => moved into custom_mods
    - "rhel-enhance_base_mods.load"
    - "rhel-enhance_base_mods.conf"
    - "rhel-enhance_custom_mods.load"
    - "rhel-enhance_custom_mods.conf"
    - "rhel-enhance_mpm_event.conf"
  notify: restart apache validate config


- name: webserver apache | config - RHEL enhancement - integrate new config structure in httpd.conf
  lineinfile:
    dest: "{{ role_apache_dist.a2conf }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp |default( omit ) }}"
    state: "{{ item.state |default('present') }}"
  with_items:
    # use ' ' instead of " " for regex
    - { line: "Include conf/mods-enabled_loader.conf",  regexp: 'Include.* conf.modules.d/\*.conf' }
    - { line: "IncludeOptional conf-enabled/*.conf",    regexp: 'IncludeOptional conf.d/\*.conf' }
    - { line: "IncludeOptional sites-enabled/*.conf" }
    # sometimes the regex can miss
    - { line: "Include conf.modules.d/*.conf",          state: "absent" }
    - { line: "IncludeOptional conf.d/*.conf",          state: "absent" }



- name: webserver apache | config - RHEL enhancement - utilities
  copy:
    src: "templates/{{ item.src }}"
    dest: "{{ item.dest |default( item.src ) }}"
    mode: "{{ item.mode |default( '0644' ) }}"
    owner: "{{ item.owner |default('root') }}"
    group: "{{ item.group |default( item.owner |default('root') ) }}"
  with_items:
    - { src: "/usr/sbin/a2enmod", mode: "0755" }
    - { src: "/usr/sbin/a2query", mode: "0755" }


- name: webserver apache | system - RHEL enhancement - utilities links
  file:
    src: "/usr/sbin/a2enmod"
    dest: "/usr/sbin/{{ item }}"
    state: link
  vars:
  with_items:
    - a2disconf
    - a2dismod
    - a2dissite
    - a2enconf
    - a2ensite

