---

- name: reload systemd-daemon
  systemd:
    daemon-reload: true
  become: yes


- name: timesyncd stop
  service:
    name: "systemd-timesyncd"
    state: stopped
  become: yes
  failed_when: false


- name: chrony stop
  service:
    name: "{{ role_chrony_dist.service }}"
    state: stopped
  become: yes

