---

- name: systemctl daemon-reload
  command: systemctl daemon-reload
  become: yes


# order is not really important with daemon-reload
- name: timesyncd stop
  service:
    name: "systemd-timesyncd"
    state: stopped
  become: yes
  failed_when: false


- name: chrony stop
  service:
    name: "{{ role_chrony_dist.service }}"
    state: stopped
