---

- name: "Monitoring cAdvisor | parameters validation"
  assert:
    that:
      - cadvisor_version |length > 0
      - cadvisor_version |regex_search('change[_ ]me', ignorecase=True) is none
      - cadvisor_compose_reverse_proxy |length > 0
      - cadvisor_compose_reverse_proxy in [ 'caddy', 'traefik' ]
    fail_msg: "Error: one of the mandatory parameters (cadvisor_*) is either not set, empty, or still with a default 'CHANGE_ME' value"
    quiet: yes


- include_role: name=_include-compose_deploy
  vars:
    arg_compose_comment: "Monitoring cAdvisor"
    arg_compose_deploy_dir: "{{ cadvisor_compose_dir }}"
    arg_compose_main_template: "{{ role_cadvisor_reverse_template.compose }}"
    arg_compose_env_template: "templates/compose.conf.j2"
    arg_compose_force_stop_on_change: yes
    arg_compose_force_pull_on_change: no
    arg_compose_conf_extra:
      - { template: "{{ role_cadvisor_reverse_template.conf }}",  dest: "conf/{{ role_cadvisor_reverse_template.conf |basename |regex_replace('.j2$', '') }}", mode: "0640" }

