{
 "title": "Home",
 "description": "Custom dashboard by HAL",
 "tags": [ "home" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dsdashboard", "query": "prometheus" },
   { "name": "job", "query": "node" },
   {
    "name": "geodc",
    "label": "Dc:",
    "query": {
     "query": "up{job=\"$job\"}"
    }
   },
   { "name": "filternetiface", "query": "^(lo|veth|br-|docker).*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;font-size:1.3em\" >\n  Domain ${__org.name}\n  <hr style=\"background-image:linear-gradient(to right, goldenrod, firebrick);height:1px;border:0; margin:auto 42%\" />\n\n</div>\n"
   }
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  { "title": "Recent alerts", "type": "alertlist", "gridPos": { "h": 14, "w": 15, "x": 0, "y": 4 } },
  {
   "title": "Alerts (Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ALERTS)", "legendFormat": "Number of alerts" }
   ]
  },
  {
   "title": "Alerts (Detail)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(ALERTS{geo=\"$geodc\"}) by (alertname, job) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\"$job\",geo=\"$geodc\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(up{job=~\"$job\",geo=\"$geodc\"} == 0 )",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Node Uptime (most recents)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "(node_time_seconds{job=~\"$job\",geo=\"$geodc\"} - node_boot_time_seconds{job=~\"$job\",geo=\"$geodc\"}) or (windows_os_time{job=~\"$job\",geo=\"$geodc\"} - windows_system_system_up_time{job=~\"$job\",geo=\"$geodc\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Global CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * sum by (geo,instance) (rate(node_cpu_seconds_total{job=\"$job\",geo=\"$geodc\",mode=\"idle\"}[5m])) / count by (geo,instance) (node_cpu_seconds_total{job=\"$job\",geo=\"$geodc\",mode=\"idle\"}))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - (100 * sum by (geo,instance) (rate(windows_cpu_time_total{job=\"$job\",geo=\"$geodc\",mode=\"idle\"}[5m])) / count by (geo,instance) (windows_cpu_time_total{job=\"$job\",geo=\"$geodc\",mode=\"idle\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Global network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (geo,instance) (rate(node_network_receive_bytes_total{job=\"$job\",geo=\"$geodc\",device!~\"$filternetiface\"}[5m]))",
     "legendFormat": "{{instance}}: recv"
    },
    {
     "expr": "sum by (geo,instance) (rate(node_network_transmit_bytes_total{job=\"$job\",geo=\"$geodc\",device!~\"$filternetiface\"}[5m]))",
     "legendFormat": "{{instance}}: sent"
    },
    {
     "expr": "sum by (geo,instance) (rate(windows_net_bytes_received_total{job=\"$job\",geo=\"$geodc\",device!~\"$filternetiface\"}[5m]))",
     "legendFormat": "{{instance}}: recv"
    },
    {
     "expr": "sum by (geo,instance) (rate(windows_net_bytes_sent_total{job=\"$job\",geo=\"$geodc\",device!~\"$filternetiface\"}[5m]))",
     "legendFormat": "{{instance}}: sent"
    }
   ]
  }
 ]
}