{
 "title": "server: Linux",
 "description": "Custom dashboard by HAL",
 "tags": [
  "device",
  "linux",
  "server"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "dsdashboard", "query": "prometheus" },
   { "name": "job", "query": "node" },
   {
    "name": "geodc",
    "label": "Dc:",
    "query": {
     "query": "up{job=\"$job\"}"
    }
   },
   {
    "name": "server",
    "label": "Server:",
    "query": {
     "query": "up{job=\"$job\",geo=\"$geodc\",os_type=\"linux\"}"
    }
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": {
     "query": "node_cpu_seconds_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}"
    }
   },
   {
    "name": "net_interface",
    "label": "Net interface",
    "query": {
     "query": "node_network_device_id{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device!~\"^(lo|veth|br-|docker).*\"}"
    }
   },
   {
    "name": "drive",
    "label": "Drive",
    "query": {
     "query": "node_disk_info{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device!~\"^(sr|dm).+\"}"
    }
   },
   {
    "name": "devicefs",
    "label": "devicefs",
    "query": {
     "query": "node_filesystem_size_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mountpoint!~\"^$|/run/user/.*\",fstype!~\"(overl|nfs|smb).*\"}"
    }
   },
   { "name": "frequency", "query": "1m,10s" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;font-size:1.3em\" >\n  Domain ${__org.name}\n  <hr style=\"background-image:linear-gradient(to right, goldenrod, firebrick);height:1px;border:0; margin:auto 42%\" />\n  Linux server : $server\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability history: $server",
   "type": "natel-discrete-panel",
   "description": "Show the total availability time for the last 7 days\n\n* Agent ping is a test from prometheus server to the agent.  \n* Uptime is the system uptime on the server. \n\nThe server can still be running, while prometheus cannot join the server agent.  \nIf the server is really unavailable, both statuses will be red / down\n\nTo allow a large relative time without losing precision, the time() interval must be explicitly set to 5m",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "min(up{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} OR on() vector(-999))",
     "legendFormat": "agent ping"
    },
    {
     "expr": "-1 * min(clamp_max(node_boot_time_seconds{job=\"$job\",geo=\"$geodc\",instance=\"$server\"},500) OR on() vector(0))",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Uptime: $server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_boot_time_seconds{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mode=\"idle\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Connected users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_logind_sessions{job=\"$job\",geo=\"$geodc\",instance=\"$server\",class=\"user\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Virtualization",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU - current usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * sum(irate(node_cpu_seconds_total{geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}[5m]))/count(node_cpu_seconds_total{geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM - current usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(100 * (node_memory_MemTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_memory_MemFree_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_memory_Cached_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} ) / node_memory_MemTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP - usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "100 - (100 * node_memory_SwapFree_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} / node_memory_SwapTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net - download",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=~\"$net_interface\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net - upload",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=~\"$net_interface\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * node_filesystem_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mountpoint=~\"$devicefs\"} / node_filesystem_size_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mountpoint=~\"$devicefs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "$server - system recap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Global System ressources: $server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (100 * sum(irate(node_cpu_seconds_total{geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}[5m])) / count(node_cpu_seconds_total{geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}))",
     "legendFormat": "cpu-total"
    },
    {
     "expr": "(100 * (node_memory_MemTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_memory_MemFree_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_memory_Cached_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} ) / node_memory_MemTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"})",
     "legendFormat": "memory"
    },
    {
     "expr": "100 - (100 * node_memory_SwapFree_bytes{geo=\"$geodc\",instance=\"$server\"} / node_memory_SwapTotal_bytes{geo=\"$geodc\",instance=\"$server\"})",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=~\"$net_interface\"}[5m])",
     "legendFormat": "{{device}}: recv"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=~\"$net_interface\"}[5m])",
     "legendFormat": "{{device}}: sent"
    }
   ]
  },
  {
   "title": "$server - CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by (mode) (irate(node_cpu_seconds_total{geo=\"$geodc\",instance=\"$server\",mode!=\"\"}[5m])) / count by (mode) (node_cpu_seconds_total{geo=\"$geodc\",instance=\"$server\",mode!=\"\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "load 1minutes"
    },
    {
     "expr": "node_load5{geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "load 5 minutes"
    },
    {
     "expr": "node_load15{geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "load 15 minutes"
    }
   ]
  },
  {
   "title": "CPU $cpu usage",
   "type": "graph",
   "description": "* user: usage for application processes (normal)  \n* nice: same as user with a lower priority  \n* system + *irq: usage for the kernel (abnormal, hardware or driver related)  \n* iowait : waiting time (abnormal, drive or network latency)  \n* steal: virtualized cpu waiting for real cpu (abnormal, too many VM)  \n\nMore information can be found here : https://www.kernel.org/doc/html/latest/admin-guide/cpu-load.html",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "repeat": "cpu",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * irate(node_cpu_seconds_total{geo=\"$geodc\",instance=\"$server\",mode!=\"idle\",cpu=\"$cpu\"}[5m])",
     "legendFormat": "cpu $cpu:  {{mode}}"
    }
   ]
  },
  {
   "title": "$server - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage (stack graph)",
   "type": "timeseries",
   "description": "* User: processes usage\n* Buffered : block device mapping cache \n* Slab : cache for memory object addresses\n* Cached : general cache (reused if required)\n\nMore information can be found here : \nhttps://www.kernel.org/doc/html/latest/filesystems/proc.html#meminfo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_memory_MemFree_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_memory_Slab_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_memory_Buffers_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_memory_Cached_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "slab cache"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "description": "vmstat swap statistics.\nThe values stands for : from disk (in) and to disk (out).   \nFor the purpose of the graph, the metrics are inverted to obtain in/out of swap.  \n\nYou can find more information here : https://www.linuxjournal.com/article/8178",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "swap total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - node_memory_SwapFree_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "swap used"
    },
    {
     "expr": "irate(node_vmstat_pswpout{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[5m])",
     "legendFormat": "swap pages in"
    },
    {
     "expr": "irate(node_vmstat_pswpin{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[5m])",
     "legendFormat": "swap pages out"
    }
   ]
  },
  {
   "title": "$server - Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$devicefs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 45 },
   "repeat": "devicefs",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mountpoint=\"$devicefs\"}",
     "legendFormat": "value"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Filesystem space usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * node_filesystem_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mountpoint=~\"$devicefs\"} / node_filesystem_size_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mountpoint=~\"$devicefs\"} )",
     "legendFormat": "{{mountpoint}} ({{device}})"
    }
   ]
  },
  {
   "title": "Filesystem inode usage",
   "type": "timeseries",
   "description": "Inodes are metadata structure keeping track of files and directories on the filesystem",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * node_filesystem_files_free{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mountpoint=~\"$devicefs\"} / node_filesystem_files{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mountpoint=~\"$devicefs\"} )",
     "legendFormat": "{{mountpoint}} ({{device}})"
    }
   ]
  },
  {
   "title": "$server - Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$drive",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 71 },
   "repeat": "drive",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_info{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$drive\"}",
     "legendFormat": "{{model}}!{{path}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Disk I/O Busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=~\"$drive\"}[5m])",
     "legendFormat": "{{device}} busy"
    }
   ]
  },
  {
   "title": "Disk I/O queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_disk_io_now{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=~\"$drive\"}",
     "legendFormat": "{{device}}: IO/s"
    }
   ]
  },
  {
   "title": "Disk I/O : $drive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "repeat": "drive",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$drive\"}[5m])",
     "legendFormat": "{{device}}: latency"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$drive\"}[5m])",
     "legendFormat": "{{device}}: read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$drive\"}[5m])",
     "legendFormat": "{{device}}: write"
    }
   ]
  },
  {
   "title": "$server - Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_running{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Kernel stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[$__rate_interval])",
     "legendFormat": "context_switches"
    },
    {
     "expr": "irate(node_intr_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[$__rate_interval])",
     "legendFormat": "interrupts"
    },
    {
     "expr": "rate(node_forks_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[$__rate_interval])",
     "legendFormat": "processes_forked"
    }
   ]
  },
  {
   "title": "sysctl stats - memory inodes (stack graph)",
   "type": "graph",
   "description": "In-memory inode handlers  \nFor more information: https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sysctl_fs_inode_state{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "inode_{{index}}"
    }
   ]
  },
  {
   "title": "sysctl stats - Dynamic pages",
   "type": "graph",
   "description": "Filesystem dynamic entries  \nFor more information: https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sysctl_fs_dentry_state{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "dentry_{{index}}"
    }
   ]
  },
  {
   "title": "sysctl stats - open file handles (VFS)",
   "type": "graph",
   "description": "Logical file handles  \nFor more information: https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sysctl_fs_file_nr{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "vfs_{{index}}"
    }
   ]
  },
  {
   "title": "sysctl stats - aio events",
   "type": "timeseries",
   "description": "System-wide number of asynchronous io requests  \nFor more information: https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sysctl_fs_aio_nr{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "aio_nr (allocated)"
    },
    {
     "expr": "node_sysctl_fs_aio_max_nr{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "aio_max"
    }
   ]
  },
  {
   "title": "$server - Network (netstat)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Netstat - TCP (stack graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(label_replace({__name__=~\"node_netstat_Tcp.*\",__name__!~\".*Octets\",job=\"$job\",geo=\"$geodc\",instance=\"$server\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")[$__rate_interval:1m])",
     "legendFormat": "{{metric_name}}"
    }
   ]
  },
  {
   "title": "Netstat - UDP (stack graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(label_replace({__name__=~\"node_netstat_Udp.*\",__name__!~\".*Octets\",job=\"$job\",geo=\"$geodc\",instance=\"$server\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")[$__rate_interval:1m])",
     "legendFormat": "{{metric_name}}"
    }
   ]
  },
  {
   "title": "Netstat - icmp (stack graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(label_replace({__name__=~\"node_netstat_Icmp.*\",__name__!~\".*Octets\",job=\"$job\",geo=\"$geodc\",instance=\"$server\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")[$__rate_interval:1m])",
     "legendFormat": "{{metric_name}}"
    }
   ]
  },
  {
   "title": "$server - Network Link : $net_interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "repeat": "net_interface",
   "targets": [
    {}
   ]
  },
  {
   "title": "Network - $net_interface (bandwidth)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}[5m])",
     "legendFormat": "received (bytes)"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}[5m])",
     "legendFormat": "sent (bytes)"
    },
    {
     "expr": "irate(node_network_carrier_changes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}[5m])",
     "legendFormat": "state change"
    }
   ]
  },
  {
   "title": "Link state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_carrier{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}",
     "legendFormat": "$net_interface"
    }
   ]
  },
  {
   "title": "Link speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_speed_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"} * 8",
     "legendFormat": "speed"
    }
   ]
  },
  {
   "title": "Network - $net_interface (packets throughtput)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "pps", "label": "Packet / sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}[5m])",
     "legendFormat": "received (packets)"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}[5m])",
     "legendFormat": "sent (packets)"
    },
    {
     "expr": "rate(node_network_receive_drop_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}[5m])",
     "legendFormat": "received - drop"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}[5m])",
     "legendFormat": "sent -  drop"
    },
    {
     "expr": "rate(node_network_receive_errs_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}[5m])",
     "legendFormat": "received - error"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}[5m])",
     "legendFormat": "sent -  error"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_mtu_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",device=\"$net_interface\"}",
     "legendFormat": "speed"
    }
   ]
  },
  {
   "title": "$server - Node agent statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus node exporter - scrape time",
     "type": "timeseries",
     "description": "Prometheus system agent",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
       "legendFormat": "scrape status : {{collector}}"
      }
     ]
    },
    {
     "title": "Prometheus node exporter - scrape status error",
     "type": "timeseries",
     "description": "Prometheus system agent  \nAny error can also occur because the module is not applicable",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "1 - node_scrape_collector_success{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
       "legendFormat": "scrape status : {{collector}}"
      },
      {
       "expr": "node_textfile_scrape_error{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
       "legendFormat": "scrape status : textfile {{collector}}"
      }
     ]
    }
   ]
  }
 ]
}