{
 "title": "server: Windows",
 "description": "Custom dashboard by HAL",
 "tags": [
  "device",
  "windows",
  "server"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m" },
   { "name": "dsdashboard", "query": "prometheus" },
   { "name": "job", "query": "node" },
   {
    "name": "geodc",
    "label": "Dc:",
    "query": {
     "query": "up{job=\"$job\"}"
    }
   },
   {
    "name": "server",
    "label": "Server:",
    "query": {
     "query": "up{job=\"$job\",geo=\"$geodc\",os_type=\"windows\"}"
    }
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": {
     "query": "windows_cpu_time_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}"
    }
   },
   {
    "name": "net_interface",
    "label": "Net interface",
    "query": {
     "query": "windows_net_current_bandwidth_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}"
    }
   },
   {
    "name": "drive",
    "label": "Drive",
    "query": {
     "query": "windows_logical_disk_size_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume!~\".*Volume.*\"}\n"
    }
   },
   {
    "name": "devicefs",
    "label": "devicefs",
    "query": {
     "query": "windows_logical_disk_size_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume!~\".*Volume.*\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;font-size:1.3em\" >\n  Domain ${__org.name}\n  <hr style=\"background-image:linear-gradient(to right, goldenrod, firebrick);height:1px;border:0; margin:auto 42%\" />\n  Windows server : $server\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability history: $server",
   "type": "natel-discrete-panel",
   "description": "Show the total availability time for the last 7 days\n\n* Agent ping is a test from prometheus server to the agent.  \n* Uptime is the system uptime on the server. \n\nThe server can still be running, while prometheus cannot join the server agent.  \nIf the server is really unavailable, both statuses will be red / down\n\nTo allow a large relative time without losing precision, the time() interval must be explicitly set to 5m",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "min(up{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} OR on() vector(-999))",
     "legendFormat": "agent ping"
    },
    {
     "expr": "-1 * min(clamp_max(windows_system_system_up_time{job=\"$job\",geo=\"$geodc\",instance=\"$server\"},500) OR on() vector(0))",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Uptime: $server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_time{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - windows_system_system_up_time{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_paging_limit_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Connected users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(windows_logon_logon_type{job=\"$job\", instance=\"$server\", status=~\"remote_interactive|interactive\"}[$__interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Virtualization",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU - current usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * sum(irate(windows_cpu_time_total{geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}[5m]))/count(windows_cpu_time_total{geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM - current usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "100 - (100 * windows_os_physical_memory_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} / windows_cs_physical_memory_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP - usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "100 - (100 * windows_os_paging_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} / windows_os_paging_limit_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net - download",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_net_bytes_received_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=~\"$net_interface\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net - upload",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_net_bytes_sent_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=~\"$net_interface\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * windows_logical_disk_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=~\"$devicefs\"} / windows_logical_disk_size_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=~\"$devicefs\"})",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "$server - system recap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Global System ressources: $server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (100 * sum(irate(windows_cpu_time_total{geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}[5m])) / count(windows_cpu_time_total{geo=\"$geodc\",instance=\"$server\",mode=\"idle\"}))",
     "legendFormat": "cpu-total"
    },
    {
     "expr": "100 - (100 * (windows_os_physical_memory_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} / windows_cs_physical_memory_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}))",
     "legendFormat": "memory"
    },
    {
     "expr": "100 - (100 * windows_os_paging_free_bytes{geo=\"$geodc\",instance=\"$server\"} / windows_os_paging_limit_bytes{geo=\"$geodc\",instance=\"$server\"})",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=~\"$net_interface\"}[5m])",
     "legendFormat": "{{nic}}: recv"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=~\"$net_interface\"}[5m])",
     "legendFormat": "{{nic}}: sent"
    }
   ]
  },
  {
   "title": "$server - CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by (mode) (irate(windows_cpu_time_total{geo=\"$geodc\",instance=\"$server\",mode!=\"\"}[5m])) / count by (mode) (windows_cpu_time_total{geo=\"$geodc\",instance=\"$server\",mode!=\"\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_system_context_switches_total{geo=\"$geodc\",instance=\"$server\"}[5m])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "windows_os_processes{geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "windows_system_threads{geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "windows_system_processor_queue_length{geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "Processor Queue Length"
    },
    {
     "expr": "irate(windows_system_system_calls_total{geo=\"$geodc\",instance=\"$server\"}[5m])",
     "legendFormat": "System calls"
    }
   ]
  },
  {
   "title": "CPU $cpu usage",
   "type": "graph",
   "description": "* user: usage for application processes (normal)  \n* nice: same as user with a lower priority  \n* system + *irq: usage for the kernel (abnormal, hardware or driver related)  \n* iowait : waiting time (abnormal, drive or network latency)  \n* steal: virtualized cpu waiting for real cpu (abnormal, too many VM)  \n\nMore information can be found here : https://www.kernel.org/doc/html/latest/admin-guide/cpu-load.html",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "repeat": "cpu",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * irate(windows_cpu_time_total{geo=\"$geodc\",instance=\"$server\",mode!=\"idle\",core=\"$cpu\"}[5m])",
     "legendFormat": "cpu $cpu:  {{mode}}"
    }
   ]
  },
  {
   "title": "$server - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage (stack graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_os_visible_memory_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "total"
    },
    {
     "expr": "windows_os_visible_memory_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - windows_os_physical_memory_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - windows_memory_system_driver_total_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "used"
    },
    {
     "expr": "windows_memory_standby_cache_normal_priority_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} + windows_memory_standby_cache_reserve_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "cached (standby)"
    },
    {
     "expr": "windows_memory_modified_page_list_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "cached (modified)"
    },
    {
     "expr": "windows_memory_system_driver_total_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "drivers"
    },
    {
     "expr": "windows_memory_free_and_zero_page_list_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_os_paging_limit_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "swap total"
    },
    {
     "expr": "windows_os_paging_limit_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - windows_os_paging_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "swap used"
    },
    {
     "expr": "irate(windows_memory_swap_pages_read_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[5m])",
     "legendFormat": "swap: out"
    },
    {
     "expr": "irate(windows_memory_swap_pages_written_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[5m])",
     "legendFormat": "swap: in"
    }
   ]
  },
  {
   "title": "Memory Working Set Usage (stack graph)",
   "type": "graph",
   "description": "RAM + Swap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_os_virtual_memory_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "Total Virtual"
    },
    {
     "expr": "windows_os_virtual_memory_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"} - windows_os_virtual_memory_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "Used Virtual"
    },
    {
     "expr": "{__name__=~\"windows_memory_.*_bytes\",job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "$server - Filesystem size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$devicefs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 54 },
   "repeat": "devicefs",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=\"$devicefs\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Separator",
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Filesystem space usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * windows_logical_disk_free_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=~\"$devicefs\"} / windows_logical_disk_size_bytes{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=~\"$devicefs\"} )",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk I/O Busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_write_latency_seconds_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=~\"$drive\"}[5m])",
     "legendFormat": "{{volume}} busy"
    }
   ]
  },
  {
   "title": "Disk I/O queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_logical_disk_requests_queued{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=~\"$drive\"}",
     "legendFormat": "{{volume}}: queue"
    }
   ]
  },
  {
   "title": "Disk I/O : $drive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "repeat": "drive",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(windows_logical_disk_read_write_latency_seconds_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=\"$drive\"}[5m])",
     "legendFormat": "{{volume}}: latency"
    },
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=\"$drive\"}[5m])",
     "legendFormat": "{{volume}}: read"
    },
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",volume=\"$drive\"}[5m])",
     "legendFormat": "{{volume}}: write"
    }
   ]
  },
  {
   "title": "$server - Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_processes{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "Kernel stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(windows_system_context_switches_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[$__rate_interval])",
     "legendFormat": "context_switches"
    },
    {
     "expr": "irate(windows_system_system_calls_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[$__rate_interval])",
     "legendFormat": "system calls"
    },
    {
     "expr": "rate(windows_system_threads{job=\"$job\",geo=\"$geodc\",instance=\"$server\"}[$__rate_interval])",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "$server - Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Netstat (stack graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(label_replace({__name__=~\"windows_net_packets.*\",__name__!~\".*packets_total\",job=\"$job\",geo=\"$geodc\",instance=\"$server\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")[$__rate_interval:1m])",
     "legendFormat": "{{metric_name}}"
    }
   ]
  },
  {
   "title": "$server - Network Link : $net_interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "repeat": "net_interface"
  },
  {
   "title": "Network - $net_interface (bandwidth)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "received (bytes)"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "sent (bytes)"
    },
    {
     "expr": "irate(windows_net_packets_received_discarded_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "received - drop"
    },
    {
     "expr": "irate(windows_net_packets_outbound_discarded_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "sent - drop"
    },
    {
     "expr": "irate(windows_net_packets_received_errors_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "received - error"
    },
    {
     "expr": "irate(windows_net_packets_outbound_errors_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "sent - error"
    }
   ]
  },
  {
   "title": "Network - $net_interface (packets)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_packets_received_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "received (packets)"
    },
    {
     "expr": "irate(windows_net_packets_sent_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "sent (packets)"
    },
    {
     "expr": "irate(windows_net_packets_received_discarded_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "received - drop"
    },
    {
     "expr": "irate(windows_net_packets_outbound_discarded_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "sent - drop"
    },
    {
     "expr": "irate(windows_net_packets_received_errors_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "received - error"
    },
    {
     "expr": "irate(windows_net_packets_outbound_errors_total{job=\"$job\",geo=\"$geodc\",instance=\"$server\",nic=\"$net_interface\"}[5m])",
     "legendFormat": "sent - error"
    }
   ]
  }
 ]
}