{
 "title": "net: icmp",
 "description": "Custom dashboard by HAL",
 "tags": [
  "network",
  "app"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dsdashboard", "query": "prometheus" },
   { "name": "job", "query": "icmp" },
   {
    "name": "geodc",
    "label": "Dc:",
    "query": {
     "query": "up{job=\"$job\"}"
    }
   },
   {
    "name": "server",
    "label": "Source:",
    "query": {
     "query": "up{job=\"$job\",geo=\"$geodc\"}"
    }
   },
   {
    "name": "remote_url_name",
    "label": "Url name:",
    "query": {
     "query": "probe_duration_seconds{job=\"$job\",geo=\"$geodc\",instance_hostname=\"$server\"}"
    }
   },
   { "name": "probe_interval", "query": "1m" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;font-size:1.3em\">\n  Domain ${__org.name}\n  <hr style=\"background-image:linear-gradient(to right, goldenrod, firebrick);height:1px;border:0; margin:auto 42%\" />\n  Module icmp\n  <p style=\"font-size:0.7em\">\n  Notice: details are limited due to packet loss not handled by the blackbox agent.\n  <a href=\"https://github.com/prometheus/blackbox_exporter/issues/115\">More information here</a>\n  </p>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "$server - Recap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "latest ping to remote url",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"$job\",geo=\"$geodc\",instance_hostname=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg_over_time(probe_success{job=\"$job\",geo=\"$geodc\",instance_hostname=\"$server\"}[5m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - probe_success{job=\"$job\",geo=\"$geodc\",instance_hostname=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ping: errors (from $geodc: $server)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "1 - probe_success{job=\"$job\",geo=\"$geodc\",instance_hostname=\"$server\"}",
     "legendFormat": "{{target}} (from {{instance_hostname}})"
    }
   ]
  },
  {
   "title": "$geodc: $server - ping polling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "server",
   "targets": [
    {}
   ]
  },
  {
   "title": "ping icmp: $remote_url_name (from $geodc)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "repeat": "remote_url_name",
   "yaxes": [
    { "format": "s", "label": "Response time" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"$job\",geo=\"$geodc\",instance_hostname=\"$server\",name=\"$remote_url_name\"}[5m])",
     "legendFormat": "response ({{target}})"
    },
    {
     "expr": "min_over_time(probe_duration_seconds{job=\"$job\",geo=\"$geodc\",instance_hostname=\"$server\",name=\"$remote_url_name\"}[5m])",
     "legendFormat": "response_min"
    },
    {
     "expr": "max_over_time(probe_duration_seconds{job=\"$job\",geo=\"$geodc\",instance_hostname=\"$server\",name=\"$remote_url_name\"}[5m])",
     "legendFormat": "response_max"
    },
    {
     "expr": "(1 - avg_over_time(probe_success{job=\"$job\",geo=\"$geodc\",instance_hostname=\"$server\",name=\"$remote_url_name\"}[5m])) * 100",
     "legendFormat": "loss ({{target}})"
    }
   ]
  }
 ]
}