---

# https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/
# use shell instead of the ansible module due to instability
# kernel is updated only when using dist-upgrade
- name: System Update | APT | normal update without kernel
  #apt: upgrade=safe
  shell: "DEBIAN_FRONTEND='noninteractive' apt-get -y -q -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' upgrade"
  args:
    warn: false
  become: yes
  throttle: "{{ system_package_update_task_throttle }}"

