---

# ref: https://salsa.debian.org/debian/reboot-notifier/
- name: System Update | APT | full update - verify reboot-notifier presence
  stat: path=/etc/default/reboot-notifier   get_checksum=no get_mime=no
  register: task_debian_reboot_notifier


- name: System Update | APT | full update - set the mail address for reboot-notifier notifications
  lineinfile:
    dest: /etc/default/reboot-notifier
    state: present
    regexp: '^NOTIFICATION_EMAIL=.*'
    line: 'NOTIFICATION_EMAIL="{{ item }}"'
  # for log output purpose
  with_items:
    - "{{ system_package_update_reboot_notifier_email }}"
  when: task_debian_reboot_notifier.stat.exists


- name: System Update | APT | full update - autoremove unused packages
  shell: "DEBIAN_FRONTEND='noninteractive' apt-get -y autoremove"
  args:
  #  warn: false
  register: task_autoremove_status
  changed_when: task_autoremove_status.stdout |length > 0
  become: true


# upgrade only if updates are available - do not ask for config change and keep current config
# notice: "full-upgrade" and "dist-upgrade" are aliases
- name: System Update | APT | full update with kernel
  shell: "DEBIAN_FRONTEND='noninteractive' apt-get -y -q -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' dist-upgrade"
  args:
  #  warn: false
  become: true
  throttle: "{{ system_package_update_task_throttle }}"


# The file is generated by APT when required
- name: System Update | APT | full update with kernel - verify if reboot is required
  stat: path=/var/run/reboot-required get_checksum=no
  register: task_reboot_required
  changed_when: task_reboot_required.stat.exists == true
  notify: reboot on update

