---

- name: "System Update | APT | full update - verify update-manager presence (Ubuntu only)"
  stat: path=/etc/update-manager/release-upgrades   get_checksum=no get_mime=no
  register: task_ubuntu_update_mgr


- name: "System Update | APT | full update - disable upgrade to next LTS release (Ubuntu only)"
  lineinfile:
    dest: /etc/update-manager/release-upgrades
    state: present
    regexp: '^Prompt *=.*'
    line: "Prompt=never"
  when: >
    task_ubuntu_update_mgr.stat.exists
    and system_package_update_ubuntu_disable_upgrade_next_lts |bool


# ref: https://salsa.debian.org/debian/reboot-notifier/
- name: "System Update | APT | full update - verify reboot-notifier presence (Debian only)"
  stat: path=/etc/default/reboot-notifier   get_checksum=no get_mime=no
  register: task_debian_reboot_notifier


- name: "System Update | APT | full update - disable reboot-notifier mail notifications (Debian only)"
  lineinfile:
    dest: /etc/default/reboot-notifier
    state: present
    regexp: '^NOTIFICATION_EMAIL=.*'
    line: 'NOTIFICATION_EMAIL=""'
  when: task_debian_reboot_notifier.stat.exists


- name: System Update | APT | full update - autoremove unused packages
  shell: apt-get -y autoremove
  args:
    warn: false
  become: true


# upgrade only if updates are available - do not ask for config change and keep current config
# notice: "full-upgrade" and "dist-upgrade" are aliases
- name: System Update | APT | full update with kernel
  shell: "DEBIAN_FRONTEND='noninteractive' apt-get -y -q -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' dist-upgrade"
  args:
    warn: false
  become: true


- name: System Update | APT | full update with kernel - verify if reboot is required
  stat: path=/var/run/reboot-required get_checksum=no
  register: task_reboot_required
  changed_when: task_reboot_required.stat.exists == true
  notify: reboot on update

