---

# Name visible as a prefix for each task description in the ansible output
# default value
arg_compose_comment: "CHANGE ME - _include-compose_deploy"


# command to use - change to docker compose if using docker compose integrated as a plugin in docker
# it is possible to set this parameter globally in the inventory
arg_compose_command: "docker-compose"


# installation directory - usually "/opt/myapp"
# it will be created if required
arg_compose_deploy_dir: ""


# path to the "docker-compose.yml" template - non-templated file allowed
arg_compose_main_template: ""


# path to the ".env" template
# any name is allowed,  in this case a ".env" symlink will be created
arg_compose_env_template: ""


# extra configuration files to install
# syntax:
#  - { template: "templates/path/to/template.file",  dest: "subdir/file.conf" }
#  - { template: "templates/path/to/template2.j2",   dest: "subdir/file2.ini",  owner: "myuser",  group: "mygroup",  mode: "0640" }
#
# the destination is a subdirectory, not the full path. It will be placed under the path in "arg_compose_dir".
# "owner" and "group" will use "root" as the default value if not specified
# "mode" will use "0644" as the default value
#
arg_compose_conf_extra: []


# set to yes to have both the _env_template and _conf_extra set as sensitive and the ansible output limited
arg_compose_conf_sensitive: no


# add an empty 'MANAGED_BY_ANSIBLE' file used as a visual marker
arg_compose_managed_by_ansible: yes


# the standard behavior will be to only execute a "compose up -d".
# set this to "yes" to have a "compose down" executed when configuration files from  _env_template and _conf_extra are updated
arg_compose_force_stop_on_change: no


# force an image pull each time, otherwise it will be executed only when one of the configuration file is updated
# notice: to work as intented, the image tag might also require to be set to 'latest'
arg_compose_force_pull_always: no


# same as _force_pull_always, but only on configuration changes.
# If set to no, the image will be pulled only when docker decides to do it. Usually on a 'up' if the version in the .env changed
arg_compose_force_pull_on_change: yes


# extra options for the "docker-compose up -d" command
# anything listed in "docker-compose up --help" goes here
arg_compose_up_options: ""


# To skip the "docker-compose up -d" execution, set this to "no"
# If skipped, the role calling "_include-compose_deploy"  will have to start the container itself, but also able to to do other stuff meanwhile.
arg_compose_up_execute: yes


# remove unused images
arg_compose_remove_old_images: no

