---

# this fact is accessible by other roles as this one is called with include:
# the stdout_lines[4:] allows to skip 4 lines
# dpkg-query returns package install history installed (ii) and removed (rc)
- name: "{{ arg_install_comment }} | pkg down+install - check if install/update is required"
  command: dpkg-query --list {{ arg_install_pkg_name }}
  args:
  #  warn: no
  register: _pkg_install_status
  become: yes
  failed_when: _pkg_install_status.rc > 1
  changed_when: >
    _pkg_install_status.stdout is defined
    and (
      _pkg_install_status.rc == 1
      or _pkg_install_status.stdout_lines[4:] is not regex("ii +")
      or _pkg_install_status.stdout_lines[4:] is not search( arg_install_pkg_version )
    )
  # only for output purpose
  with_items:
    - "{{ arg_install_pkg_version }}"


- name: "{{ arg_install_comment }} | pkg down+install - load the install/update module"
  include_tasks: debian_proc-install.yml
  when: _pkg_install_status is changed

