---

- name: Chrony NTP service | systemd - create timesyncd non-conflict directory
  file:
    path: /etc/systemd/system/systemd-timesyncd.service.d
    state: directory
    owner: root
    group: root
  become: yes


- name: Chrony NTP service | systemd - timesyncd non-conflict settings with other ntp daemons
  template:
    src: "templates/{{ item |basename }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - "/etc/systemd/system/systemd-timesyncd.service.d/disable-with-time-daemon.conf"
  become: yes
  notify: [ "timesyncd stop", "reload systemd-daemon" ]

