---
# Notice: starting with ansible > 2.9 : openssl_certificate module is renamed to x509_certificate

- name: Certificate CA | create base directory
  file: path={{ item }} state=directory mode=0700 owner=root group=root
  with_items:
    - "{{ role_ca_certificate_path | dirname }}"
  become: yes


- name: Certificate CA | OpenSSL - Private key generation
  community.crypto.openssl_privatekey:
    path: "{{ role_ca_certificate_privatekey_path }}"
    size: "{{ ca_certificate_privatekey_size }}"
    type: "{{ ca_certificate_privatekey_type }}"
    passphrase: "{{ ca_certificate_privatekey_passphrase }}"
    cipher: "auto"
    mode: "0700"
    owner: "root"
    group: "root"
    backup: yes
  become: yes
  no_log: yes


- name: Certificate CA | OpenSSL - CSR generation
  community.crypto.openssl_csr:
    path: "{{ role_ca_certificate_csr_path }}"
    privatekey_path: "{{ role_ca_certificate_privatekey_path }}"
    privatekey_passphrase: "{{ ca_certificate_privatekey_passphrase }}"
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: yes
    key_usage: "{{ ca_certificate_usages }}"
    key_usage_critical: true
    common_name: "{{ ca_certificate_common_name  }}"
    country_name: "{{ ca_certificate_country_name }}"
    organization_name: "{{ ca_certificate_organization_name }}"
    organizational_unit_name: "{{ ca_certificate_organization_unit | default(omit, true) }}"
    locality_name: "{{ ca_certificate_locality_name | default(omit, true) }}"
    state_or_province_name: "{{ ca_certificate_locality_state_or_province | default(omit, true) }}"
    email_address: "{{ ca_certificate_email_address }}"
    digest: "{{ ca_certificate_digest }}"
    # prevent creating an alt_name ['DNS:subject'] which shouldn't be present for any type of CA
    use_common_name_for_san: no
    owner: "root"
    group: "root"
    mode: "0700"
  become: yes


- name: Certificate CA | OpenSSL - Signed certificate generation
  community.crypto.x509_certificate:
    path: "{{ role_ca_certificate_path }}"
    csr_path: "{{ role_ca_certificate_csr_path }}"
    privatekey_path: "{{ role_ca_certificate_privatekey_path }}"
    privatekey_passphrase: "{{ ca_certificate_privatekey_passphrase }}"
    provider: selfsigned
    selfsigned_not_after: "{{ ca_certificate_validity_duration }}"
    selfsigned_not_before: "-1d"   # valid since yesterday
    force: "{{ ca_certificate_force_replacement |bool }}"
    mode: "0700"
    owner: "root"
    group: "root"
    backup: yes
  become: yes

