---

# the loop is here only for a more detailled log output
- name: Monitoring Prometheus agent | node - create user group
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ role_prometheus_agent_dist.user }}"


# same
- name: Monitoring Prometheus agent | node - create system user
  user:
    name: "{{ item.user }}"
    comment: "{{ item.comment }}"
    group: "{{ item.group }}"
    home: "{{ item.home }}"
    createhome: no
    password: "*"
    update_password: "always"
    shell: "/usr/sbin/nologin"
    system: yes
    state: present
  with_items:
    # yamllint disable-line rule:line-length
    - { user: "{{ role_prometheus_agent_dist.user }}",  group: "{{ role_prometheus_agent_dist.user }}",  comment: "Prometheus daemon", home: "{{ role_prometheus_agent_dist.data }}" }

