---

# oracledb exporter system requirements
role_prometheus_agent_oracledb_requirements:
  common:
    # required to allow ansible to switch to the oracledb user
    - "acl"
  debian: []
  redhat: []


# download url
role_prometheus_agent_oracledb_package_file: "oracledb_exporter.{{ prometheus_agent_oracledb_version }}.{{ role_system_lower }}-{{ role_system_arch }}.tar.gz"
# yamllint disable-line rule:line-length
role_prometheus_agent_oracledb_package_url: "https://github.com/iamseth/oracledb_exporter/releases/download/{{ prometheus_agent_oracledb_version }}/{{ role_prometheus_agent_oracledb_package_file }}"

role_prometheus_agent_oracledb_dist:
  service: "prometheus-oracledb-exporter.service"
  service_conf: "{{ role_prometheus_agent_dist.service_conf_dir }}/prometheus-oracledb-exporter"
  bin: "{{ role_prometheus_agent_dist.bin_dir }}/oracledbd_exporter"
  auth: "{{ role_prometheus_agent_dist.data }}/.oracledb_auth"

