---

# NOTICE: ansible facts are not available here

- name: Init | Bootstrap - sudo availability
  raw: "command -v sudo"
  register: system_with_sudo
  failed_when: false
  changed_when: system_with_sudo.rc != 0


# note: the commands are ran as a single command line. Keep a ';' at the end of each line
# update/makecache are required as the package cache can be not yet generated
- name: Init | Bootstrap - install sudo (debian + redhat)
  raw: >
    export SUDO_GRP=sudo;
    if [ ! -s /usr/bin/sudo ]; then
      echo 'sudo required';
      if   [ -x /usr/bin/apt ]; then /usr/bin/apt update --quiet; /usr/bin/apt --quiet -y install sudo;
      elif [ -x /usr/bin/yum ]; then /usr/bin/yum makecache --quiet; /usr/bin/yum install --quiet -y sudo; export SUDO_GRP=wheel;
      elif [ -x /usr/bin/dnf ]; then /usr/bin/dnf makecache --quiet; /usr/bin/dnf install --quiet -y sudo; export SUDO_GRP=wheel;
      else echo 'The package manager is not found or unmanaged'; exit 1;
      fi;
      sleep 3;
    fi;
    command -v sudo || exit 1;
    usermod --append --groups $SUDO_GRP  {{ ansible_user }};
  register: bootstrap_sudo
  changed_when: bootstrap_sudo.stdout is search('sudo required')
  when: system_with_sudo is changed
  become: yes
  become_method: "su"

