---

- name: system | dns - add entries to ansible master in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_default_ipv4.address }} .*"
    line: "{{ '%-16s'|format( hostvars[item].ansible_default_ipv4.address ) }}  {{ hostvars[item].ansible_hostname }}"
    state: present
  when: >
    item != '127.0.0.1' and
    item != 'localhost' and
    item not in groups['ansible'] and
    hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  become: yes

