---

# used for filling ansible_architecture_extra
role_system_arch_mapping:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armhf'
  armv6l: 'armv6'

role_system_arch: "{{ role_system_arch_mapping[ ansible_architecture ] |default(ansible_architecture) }}"

