---

# combine both without a loop to prevent listing every packages which could not exist anywmore
# the match filter expect a regex:
# => combine both _packages list and transform to string with a join('|')
# => as apt accepts wildcard, replace '*' by '.*'
# => add '^(...)$' around as it's a list and the search must be an exact match
- name: "{{ arg_install_comment }} | pkg install APT - filter packages to remove"
  set_fact:
    cacheable: no
    task_package_uninstall_list: "{{
      ansible_facts.packages | select('match', '^(' +
        ( arg_remove_packages.common + arg_remove_packages.debian ) |join('|') |replace('*','.*')
      + ')$' )  |list
    }}"

# - debug: msg="{{ task_package_uninstall_list }}"


# apt:state=absent does not handle malformed package name and will silently exit without error nor action
- name: "{{ arg_install_comment }} | pkg install APT - remove packages"
  shell: "LANG=C /usr/bin/apt-get -q -y purge {{ task_package_uninstall_list |join(' ') }} "
  args:
    warn: no
  when: task_package_uninstall_list |default([]) |length > 0
  become: yes

