---

# combine both without a loop to prevent listing every packages which could not exist anywmore
# the match filter expect a regex:
# => combine both _packages list and transform to string with a join('|')
# => as apt accepts wildcard, replace '*' by '.*'
# => add '^(...)$' around as it's a list and the search must be an exact match
- name: "{{ arg_install_comment }} | pkg install YUM - filter packages to remove"
  set_fact:
    cacheable: no
    task_package_uninstall_list: "{{
      ansible_facts.packages | select('match', '^(' +
        ( arg_remove_packages.common + arg_remove_packages.redhat ) |join('|') |replace('*','.*')
      + ')$' )  |list
    }}"


# yum:state=absent does not handle malformed package name and will silently exit without error nor action
- name: "{{ arg_install_comment }} | pkg install YUM - remove packages"
  yum:
    pkg: "{{ task_package_uninstall_list }}"
    state: absent
  when: task_package_uninstall_list |default([]) |length > 0
  become: yes

