---

# the yum module does not support python3 and the dnf module will fail on older systems => use the cmd line
- name: System Update | YUM | cache - refresh
  shell: "{{ ansible_pkg_mgr }} makecache"
  args:
    warn: false
  changed_when: false
  become: yes
  throttle: "{{ system_package_update_task_throttle }}"


# check-update will return rc=100 when updates are available
- name: System Update | YUM | check if updates are available
  shell: "{{ ansible_pkg_mgr }} check-update --quiet"
  args:
    warn: false
  register: task_update_available
  changed_when: task_update_available.rc == 100
  failed_when: task_update_available.rc > 0 and task_update_available.rc != 100
  become: yes


- name: System Update | YUM | print available updates
  debug:
    msg: "{{ task_update_available.stdout_lines }}"
  when: >
    system_package_update_print_list |bool
    and task_update_available.stdout |default('') |length > 0


- name: System Update | YUM | load corresponding mode
  include_tasks: "update-{{ display_mode.mode }}.yml"
  # mostly for log output purpose - visible when skipped
  loop_control:
    loop_var: display_mode
  with_items:
    - { mode: "{{ system_package_update_mode }}", available_updates: "{{ task_update_available is changed |ternary('yes', 'none') }}" }
  when: >
    task_update_available is changed
    or system_package_update_mode in role_supported_modes_force_update_for_reboot

