---

- name: System Update | YUM | full update - autoremove unused packages
  shell: "{{ ansible_pkg_mgr }} autoremove -y"
  args:
  #  warn: false
  register: task_autoremove_status
  changed_when: "'nothing to' not in task_autoremove_status.stdout|lower"
  become: true


# notice: "update" and "upgrade" are aliases for dnf on rhel8+ but not with yum on rhel7
# on rhel7 "yum upgrade" == "yum --obsoletes update" which are not the same
- name: System Update | YUM | full update with kernel
  shell: "{{ ansible_pkg_mgr }} update -y"
  args:
  #  warn: false
  become: true
  throttle: "{{ system_package_update_task_throttle }}"


- name: System Update | YUM | full update with kernel - verify if reboot is required
  shell: "needs-restarting -r"
  args:
  #  warn: false
  become: true
  register: task_reboot_required
  # on some versions using "-r" always has rc=1 even if a reboot is not required but the stdout will be empty
  changed_when: task_reboot_required.rc == 1 and task_reboot_required.stdout |length > 0
  failed_when: task_reboot_required.rc > 1
  notify: reboot on update

